import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import IconSvg from "@/icons/IconSvg";
import Footer from "@/components/Layouts/Footer";
import TopNav from "@/components/Layouts/TopNav";
import { CartContextProvider } from "@/context/CartContextProvider";
import { DrawerContextProvider } from "@/context/DrawerContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DrawerContextProvider>
          <CartContextProvider>
            <TopNav />
            <main className="px-10 pt-20">{children}</main>
            <Footer />
          </CartContextProvider>
        </DrawerContextProvider>
      </body>
    </html>
  );
}
